services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: hga_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hogar_geriatrico
      MYSQL_USER: hga_user
      MYSQL_PASSWORD: hga_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/hogar_geriatrico.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - hga_network

  # Aplicación Laravel (proyecto en backend2/backend)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hga_app
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:E9crzHfLf7SnBz0DAb3p7K9ZrB2h0mA9dJpk8zW9Rvw="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hogar_geriatrico
      DB_USERNAME: hga_user
      DB_PASSWORD: hga_password
    ports:
      - "8000:8000"
   # volumes:
   #   - ./backend:/var/www/html /
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "composer install --no-interaction --prefer-dist --optimize-autoloader &&
         mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache && 
         chmod -R 775 storage bootstrap/cache && 
         php artisan migrate --force && 
         php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - hga_network

  # Frontend Nginx
  frontend:
    image: nginx:alpine
    container_name: hga_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - hga_network

  # SonarQube
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - postgres_db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - hga_network

  # PostgreSQL para SonarQube
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - hga_network

volumes:
  db_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql_data:

networks:
  hga_network:
    driver: bridge

